# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dave/Desktop/practicum

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dave/Desktop/practicum

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dave/Desktop/practicum/CMakeFiles /home/dave/Desktop/practicum/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dave/Desktop/practicum/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libpayroll

# Build rule for target.
libpayroll: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libpayroll
.PHONY : libpayroll

# fast build rule for target.
libpayroll/fast:
	$(MAKE) -f payroll/CMakeFiles/libpayroll.dir/build.make payroll/CMakeFiles/libpayroll.dir/build
.PHONY : libpayroll/fast

#=============================================================================
# Target rules for targets named payroll

# Build rule for target.
payroll: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 payroll
.PHONY : payroll

# fast build rule for target.
payroll/fast:
	$(MAKE) -f payroll/CMakeFiles/payroll.dir/build.make payroll/CMakeFiles/payroll.dir/build
.PHONY : payroll/fast

#=============================================================================
# Target rules for targets named libpayroll_automoc

# Build rule for target.
libpayroll_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libpayroll_automoc
.PHONY : libpayroll_automoc

# fast build rule for target.
libpayroll_automoc/fast:
	$(MAKE) -f payroll/CMakeFiles/libpayroll_automoc.dir/build.make payroll/CMakeFiles/libpayroll_automoc.dir/build
.PHONY : libpayroll_automoc/fast

#=============================================================================
# Target rules for targets named payroll_automoc

# Build rule for target.
payroll_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 payroll_automoc
.PHONY : payroll_automoc

# fast build rule for target.
payroll_automoc/fast:
	$(MAKE) -f payroll/CMakeFiles/payroll_automoc.dir/build.make payroll/CMakeFiles/payroll_automoc.dir/build
.PHONY : payroll_automoc/fast

#=============================================================================
# Target rules for targets named employeetest

# Build rule for target.
employeetest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 employeetest
.PHONY : employeetest

# fast build rule for target.
employeetest/fast:
	$(MAKE) -f test/CMakeFiles/employeetest.dir/build.make test/CMakeFiles/employeetest.dir/build
.PHONY : employeetest/fast

#=============================================================================
# Target rules for targets named salariedtest

# Build rule for target.
salariedtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 salariedtest
.PHONY : salariedtest

# fast build rule for target.
salariedtest/fast:
	$(MAKE) -f test/CMakeFiles/salariedtest.dir/build.make test/CMakeFiles/salariedtest.dir/build
.PHONY : salariedtest/fast

#=============================================================================
# Target rules for targets named hourlytest

# Build rule for target.
hourlytest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hourlytest
.PHONY : hourlytest

# fast build rule for target.
hourlytest/fast:
	$(MAKE) -f test/CMakeFiles/hourlytest.dir/build.make test/CMakeFiles/hourlytest.dir/build
.PHONY : hourlytest/fast

#=============================================================================
# Target rules for targets named employeetest_automoc

# Build rule for target.
employeetest_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 employeetest_automoc
.PHONY : employeetest_automoc

# fast build rule for target.
employeetest_automoc/fast:
	$(MAKE) -f test/CMakeFiles/employeetest_automoc.dir/build.make test/CMakeFiles/employeetest_automoc.dir/build
.PHONY : employeetest_automoc/fast

#=============================================================================
# Target rules for targets named salariedtest_automoc

# Build rule for target.
salariedtest_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 salariedtest_automoc
.PHONY : salariedtest_automoc

# fast build rule for target.
salariedtest_automoc/fast:
	$(MAKE) -f test/CMakeFiles/salariedtest_automoc.dir/build.make test/CMakeFiles/salariedtest_automoc.dir/build
.PHONY : salariedtest_automoc/fast

#=============================================================================
# Target rules for targets named hourlytest_automoc

# Build rule for target.
hourlytest_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hourlytest_automoc
.PHONY : hourlytest_automoc

# fast build rule for target.
hourlytest_automoc/fast:
	$(MAKE) -f test/CMakeFiles/hourlytest_automoc.dir/build.make test/CMakeFiles/hourlytest_automoc.dir/build
.PHONY : hourlytest_automoc/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... libpayroll"
	@echo "... payroll"
	@echo "... libpayroll_automoc"
	@echo "... payroll_automoc"
	@echo "... employeetest"
	@echo "... salariedtest"
	@echo "... hourlytest"
	@echo "... employeetest_automoc"
	@echo "... salariedtest_automoc"
	@echo "... hourlytest_automoc"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

